export const projects = [
  {
    title: "Server-Side Rendering UI Form Generation",
    description: "Extension of Auto UI that renders fully functional forms on the server side using JSON generated by the Auto UI platform. Enables dynamic, ready-to-use forms from JSON schemas for seamless integration in MERN applications.",
    tags: ["React", "Node.js", "Express", "MongoDB", "REST API"],
    source: "https://github.com/Him-Kishan-Das/Server-Side-Rendering-UI"
  },
  {
    title: "Expense Tracker (Inertia.js/Laravel)",
    description: "Expense tracker app built with Inertia.js and Laravel, allowing users to manage and monitor expenses efficiently.",
    tags: ["Laravel", "Inertia.js", "Expense Tracking"],
    source: "https://github.com/Him-Kishan-Das/Expense-Tracker"
  },
  {
    title: "Auto UI - Dynamic Form Generation Platform",
    description: "Developed a no-code platform for generating JSON specifications for Flutter mobile apps at NIC Assam State Centre. Implemented dynamic form rendering through REST APIs with version control, user authentication and role-based permissions (Admin/Editor/Viewer), and multilingual support & export mechanisms for JSON structures.",
    tags: ["React", "Laravel", "MongoDB", "REST API", "Postman"],
    source: "" // No GitHub link provided in image
  },
  {
    title: "Exploratives - Social Media Platform",
    description: "Django-based platform for creating posts, liking, commenting, and user interactions.",
    tags: ["HTML5", "CSS", "JavaScript", "Django", "SQLite", "Git"],
    source: "https://github.com/Him-Kishan-Das/Exploratives"
  },
  {
    title: "Coder’s Mate - Online Coding Discussion Forum",
    description: "Online forum for developers to collaborate, share knowledge, and solve coding issues.",
    tags: ["HTML5", "CSS", "JavaScript", "PHP", "MySQL", "Git"],
    source: "https://github.com/Him-Kishan-Das/CodersMate"
  },
  {
    title: "TodoApp - Task Management Application",
    description: "Django-based task management application with CRUD functionality. Includes task creation, editing, deletion, and completion tracking.",
    tags: ["Django", "Python", "SQLite", "HTML", "CSS"],
    source: "https://github.com/Him-Kishan-Das/TodoApp"
  }
];